apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
    tier: data
spec:
  type: NodePort
  selector:
    app: mysql
    tier: data
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30011
