apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db2
  labels:
    type: local
spec:
  storageClassName: bbdd
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"