apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
    estado: "i"
spec:
  selector:
    matchLabels:
      app: app
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        tier: web
    spec:
      containers:
      - name: app
        image: aldosolanog/app:v1
        ports:
        - containerPort: 80