apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    estado: "i"
spec:
  selector:
    matchLabels:
      app: mysql
      tier: data
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: data
    spec:
      containers:
      - name: mysql
        image: aldosolanog/database:db
        env:
        - name: MYSQL_ROOT
          value: root
        - name: MYSQL_DATABASE
          value: dbusuarios
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: msql-pv-claim2